### ISSUE TITLE
`--start-in-tray` option fails

### ISSUE THREAD

**Issue by LanceHaverkamp** [snapcrafters/signal-desktop#4]
The `--start-in-tray` option fails in the snap version.  It does work in FlatPak & on the official Windows version.

**Comment by popey** [comment]
Thanks for the bug report. We believe this is an issue with electron builder truncating the command as passed in from outside. We'll file a bug upstream to get this fixed.

**Comment by marmarek** [comment]
snap.yaml 
```yaml
name: signal-desktop
version: 1.23.1
summary: Signal
description: Private messaging from your desktop
architectures:
- amd64
confinement: strict
grade: stable
apps:
  signal-desktop:
    command: command.sh
(...)
```

command.sh 
```sh
#!/bin/bash
exec $SNAP/bin/desktop-launch "$SNAP/app/signal-desktop"
```
The `command.sh` ignore all the arguments. It should either have `"$@"` at the end, or the command should be put into `snap.yaml` directly.

I'm not sure what part is responsible for producing this files.
